{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nevermore",
    "module": "lib-base",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "lib-base-1.0.4.aar",
          "url": "lib-base-1.0.4.aar",
          "size": 58431,
          "sha512": "36bd07042785cb96f1a22a7cd66ea2f41d4c5141333b135a7f51f291092db25f75196e58a3d3e0e68096b4186df3dbcb041d24a7de720dfaa5135748c9275e89",
          "sha256": "981718692cf4ece25478f206ade29fd7c3e7c268e8b7e600bc4b6d7c82143a1d",
          "sha1": "fb5ebb52328f0dbf5956f1f98eae9c4dd4fc775e",
          "md5": "2aebf9a08d60e2ab5dbf772c0a55991a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.tencent.tbs",
          "module": "tbssdk",
          "version": {
            "requires": "44216"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-base-1.0.4.aar",
          "url": "lib-base-1.0.4.aar",
          "size": 58431,
          "sha512": "36bd07042785cb96f1a22a7cd66ea2f41d4c5141333b135a7f51f291092db25f75196e58a3d3e0e68096b4186df3dbcb041d24a7de720dfaa5135748c9275e89",
          "sha256": "981718692cf4ece25478f206ade29fd7c3e7c268e8b7e600bc4b6d7c82143a1d",
          "sha1": "fb5ebb52328f0dbf5956f1f98eae9c4dd4fc775e",
          "md5": "2aebf9a08d60e2ab5dbf772c0a55991a"
        }
      ]
    }
  ]
}
