{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nevermore",
    "module": "device-info",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "device-info-1.1.0.aar",
          "url": "device-info-1.1.0.aar",
          "size": 51669,
          "sha512": "d3d74e286bb8b7c226adbfa422144470a900356fd6a00d2d6ba2177eef39600d86228d7b0184f9339f8f1338a43d143942452b18315ba513b922a1ad6d950ee6",
          "sha256": "d4930d8aa3a0a8c8a6b85c8ed1f0aedc613444d959676d7bb53a100509f46f8a",
          "sha1": "69c5cefcd99d16565e99ad095ef0e0a675f54e0e",
          "md5": "90ce95b6d4e99df4020e33a762e8f769"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "device-info-1.1.0.aar",
          "url": "device-info-1.1.0.aar",
          "size": 51669,
          "sha512": "d3d74e286bb8b7c226adbfa422144470a900356fd6a00d2d6ba2177eef39600d86228d7b0184f9339f8f1338a43d143942452b18315ba513b922a1ad6d950ee6",
          "sha256": "d4930d8aa3a0a8c8a6b85c8ed1f0aedc613444d959676d7bb53a100509f46f8a",
          "sha1": "69c5cefcd99d16565e99ad095ef0e0a675f54e0e",
          "md5": "90ce95b6d4e99df4020e33a762e8f769"
        }
      ]
    }
  ]
}
