{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nevermore",
    "module": "device-info",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "device-info-1.1.0.aar",
          "url": "device-info-1.1.0.aar",
          "size": 48438,
          "sha512": "dbd00229973dc24b19123c5209a3e42d5b0af2dea59009d47692450253f6ff5bcb645cd0ef7f12edbc44aa3f7d5deda5e07091066b2dfb87411eeae3b3131693",
          "sha256": "35e5ed51673873a48c12883609f4b5bacb6697d44b7d927df31bf73436da6474",
          "sha1": "075adfe736fa07aeafb0b7891ea562085fae2493",
          "md5": "7be7bda23080c4b79e1e93114d46c1a6"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "device-info-1.1.0.aar",
          "url": "device-info-1.1.0.aar",
          "size": 48438,
          "sha512": "dbd00229973dc24b19123c5209a3e42d5b0af2dea59009d47692450253f6ff5bcb645cd0ef7f12edbc44aa3f7d5deda5e07091066b2dfb87411eeae3b3131693",
          "sha256": "35e5ed51673873a48c12883609f4b5bacb6697d44b7d927df31bf73436da6474",
          "sha1": "075adfe736fa07aeafb0b7891ea562085fae2493",
          "md5": "7be7bda23080c4b79e1e93114d46c1a6"
        }
      ]
    }
  ]
}
