{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nevermore",
    "module": "lib-base",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "lib-base-1.0.0.aar",
          "url": "lib-base-1.0.0.aar",
          "size": 52440,
          "sha512": "44dc0acd1e0d437d994412e6e69de63a782ae76d82667fa803671135a82a7b628265c442cbc09349cec8d2d8c1e478669a1a3caa6dc9e5a5b04270422c88a8db",
          "sha256": "85647383755847c2432012a2d7b24374b5ce40972045951229ec0db1d56ae9db",
          "sha1": "1fd8f1bdf9e32613962da720a4c1427e24a1db46",
          "md5": "9c70db749e9d26297dd5d5ff20c5a43f"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.tencent.tbs",
          "module": "tbssdk",
          "version": {
            "requires": "44216"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-base-1.0.0.aar",
          "url": "lib-base-1.0.0.aar",
          "size": 52440,
          "sha512": "44dc0acd1e0d437d994412e6e69de63a782ae76d82667fa803671135a82a7b628265c442cbc09349cec8d2d8c1e478669a1a3caa6dc9e5a5b04270422c88a8db",
          "sha256": "85647383755847c2432012a2d7b24374b5ce40972045951229ec0db1d56ae9db",
          "sha1": "1fd8f1bdf9e32613962da720a4c1427e24a1db46",
          "md5": "9c70db749e9d26297dd5d5ff20c5a43f"
        }
      ]
    }
  ]
}
