{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nevermore",
    "module": "lib-base",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "lib-base-1.0.0.aar",
          "url": "lib-base-1.0.0.aar",
          "size": 52429,
          "sha512": "9b45bca23678834d926c5b845cd36a0dc563fee9aa3f81b893e7764b9a21cb7ade1ebceaf9152f1114b7892e80cc357f33d1b47d53641dc0b3639c522a870e7d",
          "sha256": "2b254528115ddbc44b10f4bedb137e2792f477958b237741507e09bb70b4e917",
          "sha1": "c5cce04ae8c50c111829411b2bc5f7052c3cb680",
          "md5": "e33c350f9ec3391d7197e0bec79d85e1"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.tencent.tbs",
          "module": "tbssdk",
          "version": {
            "requires": "44216"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-base-1.0.0.aar",
          "url": "lib-base-1.0.0.aar",
          "size": 52429,
          "sha512": "9b45bca23678834d926c5b845cd36a0dc563fee9aa3f81b893e7764b9a21cb7ade1ebceaf9152f1114b7892e80cc357f33d1b47d53641dc0b3639c522a870e7d",
          "sha256": "2b254528115ddbc44b10f4bedb137e2792f477958b237741507e09bb70b4e917",
          "sha1": "c5cce04ae8c50c111829411b2bc5f7052c3cb680",
          "md5": "e33c350f9ec3391d7197e0bec79d85e1"
        }
      ]
    }
  ]
}
