{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nevermore",
    "module": "lib-base",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "lib-base-1.0.1.aar",
          "url": "lib-base-1.0.1.aar",
          "size": 56220,
          "sha512": "0c433a937f069f50ffa3ab179a8ccd6c94d691920bb06a288ad6df0b3ab71e1ea49f415effdf36924b14932d61ab325f490840d9be4042aeb769d3bf27402c01",
          "sha256": "ae8a7a52541f8df99ac31edf4937f3b2268bc930f4b71b44512a243384656282",
          "sha1": "fa13e0c15f5e91d35f8c13dfb92ffa88886715dd",
          "md5": "ec43d1bff3652705e463206d9a982450"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.tencent.tbs",
          "module": "tbssdk",
          "version": {
            "requires": "44216"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib-base-1.0.1.aar",
          "url": "lib-base-1.0.1.aar",
          "size": 56220,
          "sha512": "0c433a937f069f50ffa3ab179a8ccd6c94d691920bb06a288ad6df0b3ab71e1ea49f415effdf36924b14932d61ab325f490840d9be4042aeb769d3bf27402c01",
          "sha256": "ae8a7a52541f8df99ac31edf4937f3b2268bc930f4b71b44512a243384656282",
          "sha1": "fa13e0c15f5e91d35f8c13dfb92ffa88886715dd",
          "md5": "ec43d1bff3652705e463206d9a982450"
        }
      ]
    }
  ]
}
